package com.codenvy.commons.marketo.wsdl;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.1 in JDK 6 Generated source version: 2.1
 */
@WebServiceClient(name = "MktMktowsApiService", targetNamespace = "http://www.marketo.com/mktows/",
                  wsdlLocation = "https://app-qe.marketo.com/soap/mktows/1_6?WSDL")
public class MktMktowsApiService
                                extends Service
{
    private final static Logger LOG = LoggerFactory.getLogger(MktMktowsApiService.class);
    private final static URL    MKTMKTOWSAPISERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("https://app-qe.marketo.com/soap/mktows/2_0?WSDL");
        } catch (MalformedURLException e) {
            LOG.error(e.getLocalizedMessage(), e);
        }
        MKTMKTOWSAPISERVICE_WSDL_LOCATION = url;
    }

    public MktMktowsApiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MktMktowsApiService() {
        super(MKTMKTOWSAPISERVICE_WSDL_LOCATION, new QName("http://www.marketo.com/mktows/", "MktMktowsApiService"));
    }

    /**
     * @return returns MktowsPort
     */
    @WebEndpoint(name = "MktowsApiSoapPort")
    public MktowsPort getMktowsApiSoapPort() {
        return super.getPort(new QName("http://www.marketo.com/mktows/", "MktowsApiSoapPort"), MktowsPort.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the
     *            <code>features</code> parameter will have their default values.
     * @return returns MktowsPort
     */
    @WebEndpoint(name = "MktowsApiSoapPort")
    public MktowsPort getMktowsApiSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.marketo.com/mktows/", "MktowsApiSoapPort"), MktowsPort.class, features);
    }

}
