
package com.codenvy.commons.marketo.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MktowsPort", targetNamespace = "http://www.marketo.com/mktows/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MktowsPort {


    /**
     * Send a Marketo email.
     *       
     * 
     * @param paramsDescribeMObject
     * @return
     *     returns com.marketo.mktows.wsdl.SuccessDescribeMObject
     */
    @WebMethod(action = "http://www.marketo.com/mktows/describeMObject")
    @WebResult(name = "successDescribeMObject", targetNamespace = "http://www.marketo.com/mktows/", partName = "successDescribeMObject")
    public SuccessDescribeMObject describeMObject(
        @WebParam(name = "paramsDescribeMObject", targetNamespace = "http://www.marketo.com/mktows/", partName = "paramsDescribeMObject")
        ParamsDescribeMObject paramsDescribeMObject,
        @WebParam(name="AuthenticationHeader", header=true, partName="authentication")
        AuthenticationHeaderInfo authenticationHeader);

    /**
     * Get a list campaigns.
     *       
     * 
     * @param paramsGetCampaignsForSource
     * @return
     *     returns com.marketo.mktows.wsdl.SuccessGetCampaignsForSource
     */
    @WebMethod(action = "http://www.marketo.com/mktows/getCampaignsForSource")
    @WebResult(name = "successGetCampaignsForSource", targetNamespace = "http://www.marketo.com/mktows/", partName = "successGetCampaignsForSource")
    public SuccessGetCampaignsForSource getCampaignsForSource(
        @WebParam(name = "paramsGetCampaignsForSource", targetNamespace = "http://www.marketo.com/mktows/", partName = "paramsGetCampaignsForSource")
        ParamsGetCampaignsForSource paramsGetCampaignsForSource,
        @WebParam(name="AuthenticationHeader", header=true, partName="authentication")
        AuthenticationHeaderInfo authenticationHeader);

    /**
     * Get all details about a lead.
     *       
     * 
     * @param paramsGetLead
     * @return
     *     returns com.marketo.mktows.wsdl.SuccessGetLead
     */
    @WebMethod(action = "http://www.marketo.com/mktows/getLead")
    @WebResult(name = "successGetLead", targetNamespace = "http://www.marketo.com/mktows/", partName = "successGetLead")
    public SuccessGetLead getLead(
        @WebParam(name = "paramsGetLead", targetNamespace = "http://www.marketo.com/mktows/", partName = "paramsGetLead")
        ParamsGetLead paramsGetLead,
        @WebParam(name="AuthenticationHeader", header=true, partName="authentication")
        AuthenticationHeaderInfo authenticationHeader);

    /**
     * Get all activity log details about a lead.
     *       
     * 
     * @param paramsGetLeadActivity
     * @return
     *     returns com.marketo.mktows.wsdl.SuccessGetLeadActivity
     */
    @WebMethod(action = "http://www.marketo.com/mktows/getLeadActivity")
    @WebResult(name = "successGetLeadActivity", targetNamespace = "http://www.marketo.com/mktows/", partName = "successGetLeadActivity")
    public SuccessGetLeadActivity getLeadActivity(
        @WebParam(name = "paramsGetLeadActivity", targetNamespace = "http://www.marketo.com/mktows/", partName = "paramsGetLeadActivity")
        ParamsGetLeadActivity paramsGetLeadActivity,
        @WebParam(name="AuthenticationHeader", header=true, partName="authentication")
        AuthenticationHeaderInfo authenticationHeader);

    /**
     * Get changes for all leads.
     *       
     * 
     * @param paramsGetLeadChanges
     * @return
     *     returns com.marketo.mktows.wsdl.SuccessGetLeadChanges
     */
    @WebMethod(action = "http://www.marketo.com/mktows/getLeadChanges")
    @WebResult(name = "successGetLeadChanges", targetNamespace = "http://www.marketo.com/mktows/", partName = "successGetLeadChanges")
    public SuccessGetLeadChanges getLeadChanges(
        @WebParam(name = "paramsGetLeadChanges", targetNamespace = "http://www.marketo.com/mktows/", partName = "paramsGetLeadChanges")
        ParamsGetLeadChanges paramsGetLeadChanges,
        @WebParam(name="AuthenticationHeader", header=true, partName="authentication")
        AuthenticationHeaderInfo authenticationHeader);

    /**
     * Get all details about one or more leads.
     *       
     * 
     * @param paramsGetMultipleLeads
     * @return
     *     returns com.marketo.mktows.wsdl.SuccessGetMultipleLeads
     */
    @WebMethod(action = "http://www.marketo.com/mktows/getMultipleLeads")
    @WebResult(name = "successGetMultipleLeads", targetNamespace = "http://www.marketo.com/mktows/", partName = "successGetMultipleLeads")
    public SuccessGetMultipleLeads getMultipleLeads(
        @WebParam(name = "paramsGetMultipleLeads", targetNamespace = "http://www.marketo.com/mktows/", partName = "paramsGetMultipleLeads")
        ParamsGetMultipleLeads paramsGetMultipleLeads,
        @WebParam(name="AuthenticationHeader", header=true, partName="authentication")
        AuthenticationHeaderInfo authenticationHeader);

    /**
     * Send a Marketo email.
     *       
     * 
     * @param paramsListMObjects
     * @return
     *     returns com.marketo.mktows.wsdl.SuccessListMObjects
     */
    @WebMethod(action = "http://www.marketo.com/mktows/listMObjects")
    @WebResult(name = "successListMObjects", targetNamespace = "http://www.marketo.com/mktows/", partName = "successListMObjects")
    public SuccessListMObjects listMObjects(
        @WebParam(name = "paramsListMObjects", targetNamespace = "http://www.marketo.com/mktows/", partName = "paramsListMObjects")
        ParamsListMObjects paramsListMObjects,
        @WebParam(name="AuthenticationHeader", header=true, partName="authentication")
        AuthenticationHeaderInfo authenticationHeader);

    /**
     * Perform an operation on a Marketo List, like add lead or remove lead.
     *       
     * 
     * @param paramsListOperation
     * @return
     *     returns com.marketo.mktows.wsdl.SuccessListOperation
     */
    @WebMethod(action = "http://www.marketo.com/mktows/listOperation")
    @WebResult(name = "successListOperation", targetNamespace = "http://www.marketo.com/mktows/", partName = "successListOperation")
    public SuccessListOperation listOperation(
        @WebParam(name = "paramsListOperation", targetNamespace = "http://www.marketo.com/mktows/", partName = "paramsListOperation")
        ParamsListOperation paramsListOperation,
        @WebParam(name="AuthenticationHeader", header=true, partName="authentication")
        AuthenticationHeaderInfo authenticationHeader);

    /**
     * Request to add a set of leads to a campaign.
     *       
     * 
     * @param paramsRequestCampaign
     * @return
     *     returns com.marketo.mktows.wsdl.SuccessRequestCampaign
     */
    @WebMethod(action = "http://www.marketo.com/mktows/requestCampaign")
    @WebResult(name = "successRequestCampaign", targetNamespace = "http://www.marketo.com/mktows/", partName = "successRequestCampaign")
    public SuccessRequestCampaign requestCampaign(
        @WebParam(name = "paramsRequestCampaign", targetNamespace = "http://www.marketo.com/mktows/", partName = "paramsRequestCampaign")
        ParamsRequestCampaign paramsRequestCampaign,
        @WebParam(name="AuthenticationHeader", header=true, partName="authentication")
        AuthenticationHeaderInfo authenticationHeader);

    /**
     * Create or update a lead.
     *       
     * 
     * @param paramsSyncLead
     * @return
     *     returns com.marketo.mktows.wsdl.SuccessSyncLead
     */
    @WebMethod(action = "http://www.marketo.com/mktows/syncLead")
    @WebResult(name = "successSyncLead", targetNamespace = "http://www.marketo.com/mktows/", partName = "successSyncLead")
    public SuccessSyncLead syncLead(
        @WebParam(name = "paramsSyncLead", targetNamespace = "http://www.marketo.com/mktows/", partName = "paramsSyncLead")
        ParamsSyncLead paramsSyncLead,
        @WebParam(name="AuthenticationHeader", header=true, partName="authentication")
        AuthenticationHeaderInfo authenticationHeader);

    /**
     * Create or update one or more leads.
     *       
     * 
     * @param paramsSyncMultipleLeads
     * @return
     *     returns com.marketo.mktows.wsdl.SuccessSyncMultipleLeads
     */
    @WebMethod(action = "http://www.marketo.com/mktows/syncMultipleLeads")
    @WebResult(name = "successSyncMultipleLeads", targetNamespace = "http://www.marketo.com/mktows/", partName = "successSyncMultipleLeads")
    public SuccessSyncMultipleLeads syncMultipleLeads(
        @WebParam(name = "paramsSyncMultipleLeads", targetNamespace = "http://www.marketo.com/mktows/", partName = "paramsSyncMultipleLeads")
        ParamsSyncMultipleLeads paramsSyncMultipleLeads,
        @WebParam(name="AuthenticationHeader", header=true, partName="authentication")
        AuthenticationHeaderInfo authenticationHeader);

    /**
     * Update, Insert, or Upsert custom object records
     *       
     * 
     * @param paramsSyncCustomObjects
     * @return
     *     returns com.marketo.mktows.wsdl.SuccessSyncCustomObjects
     */
    @WebMethod(action = "http://www.marketo.com/mktows/syncCustomObjects")
    @WebResult(name = "successSyncCustomObjects", targetNamespace = "http://www.marketo.com/mktows/", partName = "successSyncCustomObjects")
    public SuccessSyncCustomObjects syncCustomObjects(
        @WebParam(name = "paramsSyncCustomObjects", targetNamespace = "http://www.marketo.com/mktows/", partName = "paramsSyncCustomObjects")
        ParamsSyncCustomObjects paramsSyncCustomObjects,
        @WebParam(name="AuthenticationHeader", header=true, partName="authentication")
        AuthenticationHeaderInfo authenticationHeader);

    /**
     * Delete custom object records
     *       
     * 
     * @param paramsDeleteCustomObjects
     * @return
     *     returns com.marketo.mktows.wsdl.SuccessDeleteCustomObjects
     */
    @WebMethod(action = "http://www.marketo.com/mktows/deleteCustomObjects")
    @WebResult(name = "successDeleteCustomObjects", targetNamespace = "http://www.marketo.com/mktows/", partName = "successDeleteCustomObjects")
    public SuccessDeleteCustomObjects deleteCustomObjects(
        @WebParam(name = "paramsDeleteCustomObjects", targetNamespace = "http://www.marketo.com/mktows/", partName = "paramsDeleteCustomObjects")
        ParamsDeleteCustomObjects paramsDeleteCustomObjects,
        @WebParam(name="AuthenticationHeader", header=true, partName="authentication")
        AuthenticationHeaderInfo authenticationHeader);

    /**
     * Get custom object records
     *       
     * 
     * @param paramsGetCustomObjects
     * @return
     *     returns com.marketo.mktows.wsdl.SuccessGetCustomObjects
     */
    @WebMethod(action = "http://www.marketo.com/mktows/getCustomObjects")
    @WebResult(name = "successGetCustomObjects", targetNamespace = "http://www.marketo.com/mktows/", partName = "successGetCustomObjects")
    public SuccessGetCustomObjects getCustomObjects(
        @WebParam(name = "paramsGetCustomObjects", targetNamespace = "http://www.marketo.com/mktows/", partName = "paramsGetCustomObjects")
        ParamsGetCustomObjects paramsGetCustomObjects,
        @WebParam(name="AuthenticationHeader", header=true, partName="authentication")
        AuthenticationHeaderInfo authenticationHeader);

    /**
     * Merge Leads
     *       
     * 
     * @param paramsMergeLeads
     * @return
     *     returns com.marketo.mktows.wsdl.SuccessMergeLeads
     */
    @WebMethod(action = "http://www.marketo.com/mktows/mergeLeads")
    @WebResult(name = "successMergeLeads", targetNamespace = "http://www.marketo.com/mktows/", partName = "successMergeLeads")
    public SuccessMergeLeads mergeLeads(
        @WebParam(name = "paramsMergeLeads", targetNamespace = "http://www.marketo.com/mktows/", partName = "paramsMergeLeads")
        ParamsMergeLeads paramsMergeLeads,
        @WebParam(name="AuthenticationHeader", header=true, partName="authentication")
        AuthenticationHeaderInfo authenticationHeader);

}
